server {
    listen 80;
    server_name localhost;
    root /usr/share/nginx/html;
    index index.html;

    # ── Products Service — rutas con nombre visible ─
    location /api/products-service/ {
        proxy_pass         https://content-beauty-production-e4a1.up.railway.app/api/;
        proxy_http_version 1.1;
        proxy_set_header   Host            content-beauty-production-e4a1.up.railway.app;
        proxy_set_header   X-Real-IP       $remote_addr;
        proxy_set_header   Authorization   $http_authorization;
        proxy_pass_header  Authorization;
        proxy_ssl_server_name on;
        client_max_body_size 10M;
    }

    # ── Orders Service — rutas con nombre visible ──
    location /api/orders-service/ {
        proxy_pass         https://romantic-victory-production-e02a.up.railway.app/api/;
        proxy_http_version 1.1;
        proxy_set_header   Host            romantic-victory-production-e02a.up.railway.app;
        proxy_set_header   X-Real-IP       $remote_addr;
        proxy_set_header   Authorization   $http_authorization;
        proxy_pass_header  Authorization;
        proxy_ssl_server_name on;
    }

    # ── Payments Service — rutas con nombre visible ─
    location /api/payments-service/ {
        proxy_pass         https://prolific-success-production.up.railway.app/api/payments/;
        proxy_http_version 1.1;
        proxy_set_header   Host            prolific-success-production.up.railway.app;
        proxy_set_header   X-Real-IP       $remote_addr;
        proxy_set_header   Authorization   $http_authorization;
        proxy_pass_header  Authorization;
        proxy_ssl_server_name on;
    }

    # ── React Router ──────────────────────────────
    location / {
        try_files $uri $uri/ /index.html;
    }

    location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg|webp)$ {
        expires 1y;
        add_header Cache-Control "public, immutable";
    }

    gzip on;
    gzip_types text/plain text/css application/json application/javascript;
}
